# Should be ran on server before deployments
# docker network create spinta
# docker compose -f docker-compose.nginx.yml up -d

services:
  spinta-${BRANCH}:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./entrypoint.sh
    environment:
      - AUTHLIB_INSECURE_TRANSPORT=1
      - DB_HOST=database
      - DB_PORT=5432
    env_file:
      template.env
    networks:
       spinta:
          aliases:
             - spinta-${BRANCH}

    depends_on:
      - spinta-${BRANCH}-database

    deploy:
      resources:
        limits:
          memory: 1024M

  spinta-${BRANCH}-database:
    image: postgres:16
    environment:
      - POSTGRES_DB=spinta
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ${BRANCH}-postgres:/var/lib/postgresql/data
    networks:
      - spinta

networks:
  spinta:
    external: true
