# This workflow will install Python dependencies, run tests and lint with a
# single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests. Python 3.10-3.13

on:
  push:
    branches: [master, "[0-9]+.[0-9]+"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Build Citus + PostGIS image
        run: |
          docker build -t citus-postgis:ci .docker/citus-postgis

      - name: Start PostgreSQL (Citus + PostGIS)
        run: |
          docker run -d \
            --name postgres \
            -p 5432:5432 \
            -e POSTGRES_DB=spinta \
            -e POSTGRES_USER=ci \
            -e POSTGRES_PASSWORD=secret \
            -v "$PWD/.docker/citus-postgis/init:/docker-entrypoint-initdb.d" \
            citus-postgis:ci

      # https://github.com/marketplace/actions/mongodb-in-github-actions
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "4.0.9"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry install --all-extras -vv

      - name: Test with pytest
        env:
          SPINTA_BACKENDS__DEFAULT__DSN: postgresql://ci:secret@localhost/spinta
          SPINTA_BACKENDS__MONGO__DSN: mongodb://localhost/
        run: make test-github
