# This workflow will install Python dependencies, run tests and lint with a
# single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    # https://github.com/marketplace/actions/setup-postgresql-with-postgis
    - name: Start PostgreSQL with PostGIS
      uses: huaxk/postgis-action@v1
      with:
        # https://https://hub.docker.com/r/mdillon/postgis
        postgresql version: '11'
        postgresql password: 'secret'
        postgresql user: 'ci'
        postgresql db: 'spinta'

    # https://github.com/marketplace/actions/mongodb-in-github-actions
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: "4.0.9"

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry install -vv
        poetry install --with test

    - name: Test with pytest
      env:
        SPINTA_BACKENDS__DEFAULT__DSN: postgresql://ci:secret@localhost/spinta
        SPINTA_BACKENDS__MONGO__DSN: mongodb://localhost/
      run: |
        poetry run pytest -vvxra \
           --tb=short \
          --log-level=debug \
          --cov=spinta \
          --cov-report=term-missing \
          tests
